---
title: "R_Spatial"
author: "Isabella Ulate"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
source("setup.R")

```

# import Colorado counties with tigris

```{r}
counties <- counties(state = "CO")
```

# import roads for Larimer county

```{r}
roads <- roads(state = "CO", county = "Larimer")
```

# set tmap to interactive

```{r}
tmap_mode("view")
```
```{r}
qtm(counties)+
  qtm(roads)
```
```{r}
tm_shape(counties)+
  tm_polygons()
```

#look at the class of counties

```{r}
class(counties)
```

# point data

```{r}
poudre_points <- data.frame(name = c("Mishawaka", "Rustic", "Blue Lake Trailhead"),
                            long = c(-105.35634, -105.58159, -105.85563),
                            lat = c(40.68752, 40.69687, 40.57960))
```
```{r}
class(poudre_points)
```

#convert to spatial

```{r}
poudre_points_sf <- st_as_sf(poudre_points, coords = c("long", "lat"), crs = 4326)
```
```{r}
class(poudre_points_sf)
poudre_points_sf
```

#raster data

```{r}
elevation <- get_elev_raster(counties, z = 7)
```
```{r}
elevation
```
```{r}
qtm(elevation)
```
```{r}
tm_shape(elevation)+
  tm_raster(style = "cont", title = "Elevation (m)")
```

#the terra package

```{r}
elevation <- rast(elevation)
```
```{r}
elevation
```
```{r}
names(elevation) <- "Elevation"
```

#check for projections

```{r}
st_crs(counties)
crs(counties) == crs(elevation)
```

#project elevation layer

```{r}
elevation_prj <- terra::project(elevation, counties)
```

#crop elevation to county extent

```{r}
elevation_crop <- crop(elevation, ext(counties))
qtm(elevation_crop)
```

#read and write spatial data
#save sf/vector data
```{r}
write_sf(counties,"data/counties.shp")
```

#save raster data
```{r}
writeRaster(elevation_crop, "data/elevation.tif")
```

#save.RData

```{r}
save(counties, roads, file = "data/spatial_objects.RData")
```
#test saved objects
```{r}
rm(counties, roads)
```
```{r}
load("data/spatial_objects.RData")
```

